### ISSUE TITLE
Why does it take 48 hours for my key to expire?

### ISSUE THREAD

**Issue by BuckinghamStudios** [nodusclient/gatekeep#1]

**Comment by 0xAda** [comment]
Because the key mojang gave you expires in 48 hours. If you start your game
in 40 hours time, it will expire in 8 hours

**Comment by Geometer1729** [comment]
Does asking for a key expire all previous keys? If not could you make a daemon to request a key every few minutes so there's always a key you can use that will expire shortly?

**Comment by treppenhaus** [comment]
@Geometer1729 thinking of this, its currently possible to play with the same account on multiple servers at the same time so in theory it should be possible
